CREATE TABLE VENDOR_CHECK
(
	VENDOR_CHECK_ID NUMERIC(16) NOT NULL PRIMARY KEY,
	DECIMAL_DIGIT NUMERIC(5, 3) NOT NULL,
	INTEGER_NON_DIGIT NUMERIC(5, 0) NOT NULL,
	LARGE_CHARACTER TEXT NOT NULL
)  ;

